#cloud-config
###############################################################################
# VM CUSTOMIZATION - METADATA
###############################################################################
# This file contains the cloud-init metadata configuration for the VM
# It defines hostname, instance ID, and network configuration
###############################################################################

###############################################################################
# IDENTITY CONFIGURATION
###############################################################################
# Set the hostname of the VM to the provided name variable
local-hostname: ${name}

# Set a unique instance ID for the VM
instance-id: centos-${name}

###############################################################################
# NETWORK CONFIGURATION
###############################################################################
# Network configuration using Netplan v2 format
network:
  version: 2  # Use Netplan version 2
  ethernets:  # Configure Ethernet interfaces
    ens192:   # First network adapter (typically VMware's VMXNET3)
      dhcp4: true  # Disable DHCP, use static IP configuration

###############################################################################
# STORAGE CONFIGURATION
###############################################################################
# Automatically grow the root partition to use available space
growpart:
  mode: auto  # Automatically resize partitions
  devices: ['/dev/sda2']  # Target the second partition on the first disk (typically root)
  ignore_growroot_disabled: true  # Proceed even if growroot is disabled

###############################################################################
# BOOT CONFIGURATION
###############################################################################
# Wait for network to be available before proceeding with boot
wait-on-network:
  ipv4: true  # Wait for IPv4 connectivity